// ============================================================
// Picapool ID Utilities
// ============================================================

import { v4 as uuidv4 } from 'uuid';

/**
 * Generate a UUID v4 for internal use.
 * Never displayed to the user.
 */
export function generateId(): string {
  return uuidv4();
}

/**
 * Generate a session ID combining timestamp + short random.
 * Used for grouping analytics events.
 */
export function generateSessionId(): string {
  const ts = Date.now().toString(36).toUpperCase();
  const rand = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `SES-${ts}-${rand}`;
}

/**
 * Display IDs (KN-001, etc.) are generated by Apps Script.
 * This is a client-side placeholder for display before sync.
 */
export function placeholderDisplayId(prefix: string): string {
  return `${prefix}-PENDING`;
}

/**
 * Format duration in seconds to a human-readable string.
 */
export function formatDuration(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  if (mins < 60) return secs > 0 ? `${mins}m ${secs}s` : `${mins}m`;
  const hrs = Math.floor(mins / 60);
  const remMins = mins % 60;
  return `${hrs}h ${remMins}m`;
}

/**
 * Calculate duration in seconds between two ISO strings.
 */
export function calculateDuration(startedAt: string, endedAt: string): number {
  return Math.round(
    (new Date(endedAt).getTime() - new Date(startedAt).getTime()) / 1000
  );
}
